### ISSUE TITLE
update pkg devel workflow

### ISSUE THREAD

**Issue by achubaty** [ianmseddy/LandR.CS#5]
In prepping caribou and bird MSes, I'd like to get this repo as close to "operational" as possible in anticipation that more people will start looking at / using it .

- [x] add github actions to check package automatically (#3, #4)
- [x] add README (part of #3)
- [x] fix name of Rstudio project file (part of #3)
- [x] update DESCRIPTION with authorship info etc. (started in #2)
- [x] bump package version on `master` to `0.0.3` (#7)
- [x] create `development` branch with version `0.0.3.9000`
